//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEcole.Resources.Views.Etudiant {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Details {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Details() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestionEcole.Resources.Views.Etudiant.Details", typeof(Details).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Average Grade is : .
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course:.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of the Marks.
        /// </summary>
        public static string DetailsNotes {
            get {
                return ResourceManager.GetString("DetailsNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Courses of.
        /// </summary>
        public static string LegendCourses {
            get {
                return ResourceManager.GetString("LegendCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lessons of.
        /// </summary>
        public static string LegendStudent {
            get {
                return ResourceManager.GetString("LegendStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson&apos;s End:.
        /// </summary>
        public static string LessonsEnd {
            get {
                return ResourceManager.GetString("LessonsEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson&apos;s Start:.
        /// </summary>
        public static string LessonsStart {
            get {
                return ResourceManager.GetString("LessonsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson&apos;s Subject:.
        /// </summary>
        public static string LessonSubject {
            get {
                return ResourceManager.GetString("LessonSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe To a Lesson.
        /// </summary>
        public static string Sinscrire {
            get {
                return ResourceManager.GetString("Sinscrire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string ViewBagTitle {
            get {
                return ResourceManager.GetString("ViewBagTitle", resourceCulture);
            }
        }
    }
}
